# Generated by Django 6.0.6 on 2026-06-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_itempedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CC', 'Cartão de Crédito'), ('BOL', 'Boleto Bancário')], default='PIX', max_length=3),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado'), ('X', 'Cancelado')], default='C', max_length=1),
        ),
    ]
